export const SET_LOCATION = 'SET_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';

export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';
export const LOGIN_CUSTOMER_SUCCESS = 'LOGIN_CUSTOMER_SUCCESS';
export const LOGIN_CUSTOMER_FAILED = 'LOGIN_CUSTOMER_FAILED';

export const REGISTER_VENDOR = 'REGISTER_VENDOR';
export const REGISTER_VENDOR_SUCCESS = 'REGISTER_VENDOR_SUCCESS';
export const REGISTER_VENDOR_FAILED = 'REGISTER_VENDOR_FAILED';

export const VERIFY_OTP_CUSTOMER = 'VERIFY_OTP_CUSTOMER';
export const VERIFY_OTP_CUSTOMER_SUCCESS = 'VERIFY_OTP_CUSTOMER_SUCCESS';
export const VERIFY_OTP_CUSTOMER_FAILED = 'VERIFY_OTP_CUSTOMER_FAILED';

export const VERIFY_OTP_VENDOR = 'VERIFY_OTP_VENDOR';
export const VERIFY_OTP_VENDOR_SUCCESS = 'VERIFY_OTP_VENDOR_SUCCESS';
export const VERIFY_OTP_VENDOR_FAILED = 'VERIFY_OTP_VENDOR_FAILED';

export const UPDATE_USER_CUSTOMER = 'UPDATE_USER_CUSTOMER';
export const UPDATE_USER_CUSTOMER_SUCCESS = 'UPDATE_USER_CUSTOMER_SUCCESS';
export const UPDATE_USER_CUSTOMER_FAILED = 'UPDATE_USER_CUSTOMER_FAILED';

export const UPDATE_VENDOR_PROFILE = 'UPDATE_VENDOR_PROFILE';
export const UPDATE_VENDOR_PROFILE_SUCCESS = 'UPDATE_VENDOR_PROFILE_SUCCESS';
export const UPDATE_VENDOR_PROFILE_FAILED = 'UPDATE_VENDOR_PROFILE_FAILED';

export const SAVE_BUSINESS_ADDRESS = 'SAVE_BUSINESS_ADDRESS';
export const SAVE_BUSINESS_ADDRESS_SUCCESS = 'SAVE_BUSINESS_ADDRESS_SUCCESS';
export const SAVE_BUSINESS_ADDRESS_FAILED = 'SAVE_BUSINESS_ADDRESS_FAILED';

export const GET_VENDOR_CATEGORIES = 'GET_VENDOR_CATEGORIES';
export const GET_VENDOR_CATEGORIES_SUCCESS = 'GET_VENDOR_CATEGORIES_SUCCESS';
export const GET_VENDOR_CATEGORIES_FAILED = 'GET_VENDOR_CATEGORIES_FAILED';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED';

export const GET_SERVICES_BY_CATEGORY = 'GET_SERVICES_BY_CATEGORY';
export const GET_SERVICES_BY_CATEGORY_SUCCESS =
  'GET_SERVICES_BY_CATEGORY_SUCCESS';
export const GET_SERVICES_BY_CATEGORY_FAILED =
  'GET_SERVICES_BY_CATEGORY_FAILED';

export const GET_VENDOR_SERVICES_BY_CATEGORY =
  'GET_VENDOR_SERVICES_BY_CATEGORY';
export const GET_VENDOR_SERVICES_BY_CATEGORY_SUCCESS =
  'GET_VENDOR_SERVICES_BY_CATEGORY_SUCCESS';
export const GET_VENDOR_SERVICES_BY_CATEGORY_FAILED =
  'GET_VENDOR_SERVICES_BY_CATEGORY_FAILED';

export const GET_VENDOR_USER_DETAILS = 'GET_VENDOR_USER_DETAILS';
export const GET_VENDOR_USER_DETAILS_SUCCESS =
  'GET_VENDOR_USER_DETAILS_SUCCESS';
export const GET_VENDOR_USER_DETAILS_FAILED = 'GET_VENDOR_USER_DETAILS_FAILED';

export const SAVE_VENDOR_SERVICES = 'SAVE_VENDOR_SERVICES';
export const SAVE_VENDOR_SERVICES_SUCCESS = 'SAVE_VENDOR_SERVICES_SUCCESS';
export const SAVE_VENDOR_SERVICES_FAILED = 'SAVE_VENDOR_SERVICES_FAILED';

export const RESEND_OTP_VENDOR = 'RESEND_OTP_VENDOR';
export const RESEND_OTP_VENDOR_SUCCESS = 'RESEND_OTP_VENDOR_SUCCESS';
export const RESEND_OTP_VENDOR_FAILED = 'RESEND_OTP_VENDOR_FAILED';

export const LOGIN_VENDOR = 'LOGIN_VENDOR';
export const LOGIN_VENDOR_SUCCESS = 'LOGIN_VENDOR_SUCCESS';
export const LOGIN_VENDOR_FAILED = 'LOGIN_VENDOR_FAILED';

export const GET_MY_AVAILABILITY = 'GET_MY_AVAILABILITY';
export const GET_MY_AVAILABILITY_SUCCESS = 'GET_MY_AVAILABILITY_SUCCESS';
export const GET_MY_AVAILABILITY_FAILED = 'GET_MY_AVAILABILITY_FAILED';

export const UPDATE_MY_AVAILABILITY = 'UPDATE_MY_AVAILABILITY';
export const UPDATE_MY_AVAILABILITY_SUCCESS = 'UPDATE_MY_AVAILABILITY_SUCCESS';
export const UPDATE_MY_AVAILABILITY_FAILED = 'UPDATE_MY_AVAILABILITY_FAILED';

export const LOGOUT = 'LOGOUT';

export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const UPDATE_USER_LOCATION_SUCCESS = 'UPDATE_USER_LOCATION_SUCCESS';
export const UPDATE_USER_LOCATION_FAILED = 'UPDATE_USER_LOCATION_FAILED';

export const SAVE_CUSTOMER_ADDRESS = 'SAVE_CUSTOMER_ADDRESS';
export const SAVE_CUSTOMER_ADDRESS_SUCCESS = 'SAVE_CUSTOMER_ADDRESS_SUCCESS';
export const SAVE_CUSTOMER_ADDRESS_FAILED = 'SAVE_CUSTOMER_ADDRESS_FAILED';

export const UPDATE_CUSTOMER_ADDRESS = 'UPDATE_CUSTOMER_ADDRESS';
export const UPDATE_CUSTOMER_ADDRESS_SUCCESS =
  'UPDATE_CUSTOMER_ADDRESS_SUCCESS';
export const UPDATE_CUSTOMER_ADDRESS_FAILED = 'UPDATE_CUSTOMER_ADDRESS_FAILED';

export const GET_CUSTOMER_ADDRESSES = 'GET_CUSTOMER_ADDRESSES';
export const GET_CUSTOMER_ADDRESSES_SUCCESS = 'GET_CUSTOMER_ADDRESSES_SUCCESS';
export const GET_CUSTOMER_ADDRESSES_FAILED = 'GET_CUSTOMER_ADDRESSES_FAILED';

export const DELETE_CUSTOMER_ADDRESS = 'DELETE_CUSTOMER_ADDRESS';
export const DELETE_CUSTOMER_ADDRESS_SUCCESS =
  'DELETE_CUSTOMER_ADDRESS_SUCCESS';
export const DELETE_CUSTOMER_ADDRESS_FAILED = 'DELETE_CUSTOMER_ADDRESS_FAILED';

export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILED = 'CREATE_BOOKING_FAILED';

export const GET_BOOKING_BY_ID = 'GET_BOOKING_BY_ID';
export const GET_BOOKING_BY_ID_SUCCESS = 'GET_BOOKING_BY_ID_SUCCESS';
export const GET_BOOKING_BY_ID_FAILED = 'GET_BOOKING_BY_ID_FAILED';

export const UPDATE_BOOKING_ADDRESS = 'UPDATE_BOOKING_ADDRESS';
export const UPDATE_BOOKING_ADDRESS_SUCCESS = 'UPDATE_BOOKING_ADDRESS_SUCCESS';
export const UPDATE_BOOKING_ADDRESS_FAILED = 'UPDATE_BOOKING_ADDRESS_FAILED';

export const GET_VENDOR_BOOKINGS = 'GET_VENDOR_BOOKINGS';
export const GET_VENDOR_BOOKINGS_SUCCESS = 'GET_VENDOR_BOOKINGS_SUCCESS';
export const GET_VENDOR_BOOKINGS_FAILED = 'GET_VENDOR_BOOKINGS_FAILED';

export const ACCEPT_VENDOR_BOOKING = 'ACCEPT_VENDOR_BOOKING';
export const ACCEPT_VENDOR_BOOKING_SUCCESS = 'ACCEPT_VENDOR_BOOKING_SUCCESS';
export const ACCEPT_VENDOR_BOOKING_FAILED = 'ACCEPT_VENDOR_BOOKING_FAILED';

export const CANCEL_VENDOR_BOOKING = 'CANCEL_VENDOR_BOOKING';
export const CANCEL_VENDOR_BOOKING_SUCCESS = 'CANCEL_VENDOR_BOOKING_SUCCESS';
export const CANCEL_VENDOR_BOOKING_FAILED = 'CANCEL_VENDOR_BOOKING_FAILED';

export const VENDOR_SEND_OTP = 'VENDOR_SEND_OTP';
export const VENDOR_SEND_OTP_SUCCESS = 'VENDOR_SEND_OTP_SUCCESS';
export const VENDOR_SEND_OTP_FAILED = 'VENDOR_SEND_OTP_FAILED';

export const VENDOR_RESEND_OTP = 'VENDOR_RESEND_OTP';
export const VENDOR_RESEND_OTP_SUCCESS = 'VENDOR_RESEND_OTP_SUCCESS';
export const VENDOR_RESEND_OTP_FAILED = 'VENDOR_RESEND_OTP_FAILED';

export const VENDOR_VERIFY_OTP = 'VENDOR_VERIFY_OTP';
export const VENDOR_VERIFY_OTP_SUCCESS = 'VENDOR_VERIFY_OTP_SUCCESS';
export const VENDOR_VERIFY_OTP_FAILED = 'VENDOR_VERIFY_OTP_FAILED';
