export const SET_LOCATION = 'SET_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';

export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';
export const LOGIN_CUSTOMER_SUCCESS = 'LOGIN_CUSTOMER_SUCCESS';
export const LOGIN_CUSTOMER_FAILED = 'LOGIN_CUSTOMER_FAILED';

export const REGISTER_VENDOR = 'REGISTER_VENDOR';
export const REGISTER_VENDOR_SUCCESS = 'REGISTER_VENDOR_SUCCESS';
export const REGISTER_VENDOR_FAILED = 'REGISTER_VENDOR_FAILED';

export const VERIFY_OTP_CUSTOMER = 'VERIFY_OTP_CUSTOMER';
export const VERIFY_OTP_CUSTOMER_SUCCESS = 'VERIFY_OTP_CUSTOMER_SUCCESS';
export const VERIFY_OTP_CUSTOMER_FAILED = 'VERIFY_OTP_CUSTOMER_FAILED';

export const VERIFY_OTP_VENDOR = 'VERIFY_OTP_VENDOR';
export const VERIFY_OTP_VENDOR_SUCCESS = 'VERIFY_OTP_VENDOR_SUCCESS';
export const VERIFY_OTP_VENDOR_FAILED = 'VERIFY_OTP_VENDOR_FAILED';

export const UPDATE_USER_CUSTOMER = 'UPDATE_USER_CUSTOMER';
export const UPDATE_USER_CUSTOMER_SUCCESS = 'UPDATE_USER_CUSTOMER_SUCCESS';
export const UPDATE_USER_CUSTOMER_FAILED = 'UPDATE_USER_CUSTOMER_FAILED';

export const UPDATE_VENDOR_PROFILE = 'UPDATE_VENDOR_PROFILE';
export const UPDATE_VENDOR_PROFILE_SUCCESS = 'UPDATE_VENDOR_PROFILE_SUCCESS';
export const UPDATE_VENDOR_PROFILE_FAILED = 'UPDATE_VENDOR_PROFILE_FAILED';

export const SAVE_BUSINESS_ADDRESS = 'SAVE_BUSINESS_ADDRESS';
export const SAVE_BUSINESS_ADDRESS_SUCCESS = 'SAVE_BUSINESS_ADDRESS_SUCCESS';
export const SAVE_BUSINESS_ADDRESS_FAILED = 'SAVE_BUSINESS_ADDRESS_FAILED';

export const GET_VENDOR_CATEGORIES = 'GET_VENDOR_CATEGORIES';
export const GET_VENDOR_CATEGORIES_SUCCESS = 'GET_VENDOR_CATEGORIES_SUCCESS';
export const GET_VENDOR_CATEGORIES_FAILED = 'GET_VENDOR_CATEGORIES_FAILED';

export const GET_SERVICES_BY_CATEGORY = 'GET_SERVICES_BY_CATEGORY';
export const GET_SERVICES_BY_CATEGORY_SUCCESS = 'GET_SERVICES_BY_CATEGORY_SUCCESS';
export const GET_SERVICES_BY_CATEGORY_FAILED = 'GET_SERVICES_BY_CATEGORY_FAILED';

export const SAVE_VENDOR_SERVICES = 'SAVE_VENDOR_SERVICES';
export const SAVE_VENDOR_SERVICES_SUCCESS = 'SAVE_VENDOR_SERVICES_SUCCESS';
export const SAVE_VENDOR_SERVICES_FAILED = 'SAVE_VENDOR_SERVICES_FAILED';

export const RESEND_OTP_VENDOR = 'RESEND_OTP_VENDOR';
export const RESEND_OTP_VENDOR_SUCCESS = 'RESEND_OTP_VENDOR_SUCCESS';
export const RESEND_OTP_VENDOR_FAILED = 'RESEND_OTP_VENDOR_FAILED';

export const LOGIN_VENDOR = 'LOGIN_VENDOR';
export const LOGIN_VENDOR_SUCCESS = 'LOGIN_VENDOR_SUCCESS';
export const LOGIN_VENDOR_FAILED = 'LOGIN_VENDOR_FAILED';

export const LOGOUT = 'LOGOUT';

