export const SET_LOCATION = 'SET_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';

export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';
export const LOGIN_CUSTOMER_SUCCESS = 'LOGIN_CUSTOMER_SUCCESS';
export const LOGIN_CUSTOMER_FAILED = 'LOGIN_CUSTOMER_FAILED';

export const VERIFY_OTP_CUSTOMER = 'VERIFY_OTP_CUSTOMER';
export const VERIFY_OTP_CUSTOMER_SUCCESS = 'VERIFY_OTP_CUSTOMER_SUCCESS';
export const VERIFY_OTP_CUSTOMER_FAILED = 'VERIFY_OTP_CUSTOMER_FAILED';

export const UPDATE_USER_CUSTOMER = 'UPDATE_USER_CUSTOMER';
export const UPDATE_USER_CUSTOMER_SUCCESS = 'UPDATE_USER_CUSTOMER_SUCCESS';
export const UPDATE_USER_CUSTOMER_FAILED = 'UPDATE_USER_CUSTOMER_FAILED';
